"use client";

import React, { useState } from "react";
import { Card, Button, StatusBadge } from "@/components/ui";
import {
  FileTextIcon,
  DownloadIcon,
  ShieldCheckIcon,
  CheckCircleIcon,
  AlertTriangleIcon,
} from "@/components/icons";

interface AuditReportItem {
  id: string;
  report_name: string;
  tender_id: string;
  generated_at: string;
  generated_by: string;
  format: "PDF" | "JSON" | "EXCEL";
  status: "READY" | "GENERATING";
  type: string;
}

const SAMPLE_REPORTS: AuditReportItem[] = [
  {
    id: "REP-2024-001",
    report_name: "Tender_CPCL_2024_09_Comparative_Statement_CST.pdf",
    tender_id: "CPCL/PROC/SAFETY/2024/09",
    generated_at: "28-Aug-2024 15:30",
    generated_by: "S. Ramanathan (Procurement Officer)",
    format: "PDF",
    status: "READY",
    type: "Comparative Statement (CST)",
  },
  {
    id: "REP-2024-002",
    report_name: "ABC_Safety_Solutions_Traceability_Dossier.pdf",
    tender_id: "CPCL/PROC/SAFETY/2024/09",
    generated_at: "28-Aug-2024 15:45",
    generated_by: "System Automated Evaluation",
    format: "PDF",
    status: "READY",
    type: "Bidder Compliance Audit Trail",
  },
  {
    id: "REP-2024-003",
    report_name: "Vigilance_Debarment_MultiPortal_Clearance_Log.pdf",
    tender_id: "CPCL/PROC/SAFETY/2024/09",
    generated_at: "28-Aug-2024 16:00",
    generated_by: "System Automated Evaluation",
    format: "PDF",
    status: "READY",
    type: "Statutory & Vigilance Audit",
  },
  {
    id: "REP-2024-004",
    report_name: "CPCL_Safety_Tender_Complete_Audit_Bundle.json",
    tender_id: "CPCL/PROC/SAFETY/2024/09",
    generated_at: "28-Aug-2024 16:10",
    generated_by: "System Automated Evaluation",
    format: "JSON",
    status: "READY",
    type: "Machine-Readable Evidence Package",
  },
];

export default function ReportsPage() {
  const [downloading, setDownloading] = useState<string | null>(null);

  function handleDownload(reportId: string, name: string) {
    setDownloading(reportId);
    setTimeout(() => {
      setDownloading(null);
      alert(`Downloaded: ${name}`);
    }, 800);
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <span className="text-xs font-bold uppercase tracking-wider text-blue-600">
            Export & Verification Dossiers
          </span>
          <h1 className="text-2xl font-extrabold text-slate-900">
            Audit Reports & Exportable Statements
          </h1>
          <p className="text-xs text-slate-500">
            Download CAG and CVC compliant evaluation dossiers, Comparative Statements (CST), and raw evidence bundles.
          </p>
        </div>

        <Button size="sm" className="bg-blue-700 hover:bg-blue-800">
          <DownloadIcon className="size-4" />
          Generate New Evaluation Dossier
        </Button>
      </div>

      {/* Reports Grid */}
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        {SAMPLE_REPORTS.map((report) => (
          <Card key={report.id} className="p-5 flex flex-col justify-between">
            <div>
              <div className="flex items-start justify-between">
                <div className="flex items-center gap-2.5">
                  <div className="rounded-lg bg-blue-50 p-2 text-blue-700">
                    <FileTextIcon className="size-5" />
                  </div>
                  <div>
                    <span className="rounded bg-slate-100 px-2 py-0.5 text-[10px] font-bold text-slate-600">
                      {report.type}
                    </span>
                    <h2 className="mt-1 text-sm font-bold text-slate-900">
                      {report.report_name}
                    </h2>
                  </div>
                </div>
                <span className="rounded bg-emerald-50 px-2 py-0.5 text-[10px] font-bold text-emerald-700">
                  {report.format}
                </span>
              </div>

              <div className="mt-4 space-y-1.5 text-xs text-slate-600">
                <div className="flex justify-between">
                  <span className="text-slate-400">Tender Reference:</span>
                  <span className="font-mono font-medium text-slate-800">{report.tender_id}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-400">Generated By:</span>
                  <span className="font-medium text-slate-800">{report.generated_by}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-400">Timestamp:</span>
                  <span className="font-medium text-slate-800">{report.generated_at}</span>
                </div>
              </div>
            </div>

            <div className="mt-5 border-t pt-3 flex items-center justify-between">
              <span className="text-[11px] text-emerald-600 font-semibold flex items-center gap-1">
                <CheckCircleIcon className="size-3.5" />
                Verified Immutable
              </span>
              <Button
                size="sm"
                variant="outline"
                loading={downloading === report.id}
                onClick={() => handleDownload(report.id, report.report_name)}
              >
                <DownloadIcon className="size-3.5" />
                Download
              </Button>
            </div>
          </Card>
        ))}
      </div>
    </div>
  );
}
